//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons_badges
    {
        public int id { get; set; }
        public int people_id { get; set; }
        public int badge_id { get; set; }
    
        public virtual Badge Badge { get; set; }
        public virtual Person Person { get; set; }
    }
}
